In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("dataset.csv")

In [3]:
df

feeling.nervous panic breathing.rapidly sweating  \
0                 yes   yes               yes      yes   
1                  no    no                no       no   
2                  no    no                no       no   
3                  no    no                no       no   
4                  no    no                no       no   
...               ...   ...               ...      ...   
40955             yes   yes               yes      yes   
40956              no    no                no       no   
40957              no    no                no       no   
40958              no    no                no       no   
40959              no    no                no       no   

      trouble.in.concentration having.trouble.in.sleeping  \
0                          yes                        yes   
1                           no                         no   
2                           no                         no   
3                           no                         no   
4                           no                         no   
...                        ...                        ...   
40955                      yes                        yes   
40956                       no                         no   
40957                       no                         no   
40958                       no                         no   
40959                       no                         no   

      having.trouble.with.work hopelessness anger over.react  ... weight.gain  \
0                           no           no    no         no  ...          no   
1                          yes          yes   yes        yes  ...          no   
2                           no           no    no         no  ...         yes   
3                           no           no    no         no  ...          no   
4                           no           no    no         no  ...          no   
...                        ...          ...   ...        ...  ...         ...   
40955                       no           no    no         no  ...          no   
40956                      yes          yes   yes        yes  ...          no   
40957                       no           no    no         no  ...         yes   
40958                       no           no    no         no  ...          no   
40959                       no           no    no         no  ...          no   

      material.possessions introvert popping.up.stressful.memory  \
0                       no        no                          no   
1                       no        no                          no   
2                      yes       yes                          no   
3                       no        no                         yes   
4                       no        no                          no   
...                    ...       ...                         ...   
40955                   no        no                          no   
40956                   no        no                          no   
40957                  yes       yes                          no   
40958                   no        no                         yes   
40959                   no        no                          no   

      having.nightmares avoids.people.or.activities feeling.negative  \
0                    no                          no               no   
1                    no                          no               no   
2                    no                          no               no   
3                   yes                         yes              yes   
4                    no                          no               no   
...                 ...                         ...              ...   
40955                no                          no               no   
40956                no                          no               no   
40957                no                          no               no   
40958               yes                         yes              y

In [4]:
df.index

RangeIndex(start=0, stop=40960, step=1)

In [9]:
Y = df['Disorder'].copy()

In [11]:
for column in df.columns:
    df[column] = df[column].map({'yes' : 1, 'no' : 0})

In [14]:
df.drop('Disorder', axis = 1, inplace = True)

In [15]:
df.dtypes

feeling.nervous                int64
panic                          int64
breathing.rapidly              int64
sweating                       int64
trouble.in.concentration       int64
having.trouble.in.sleeping     int64
having.trouble.with.work       int64
hopelessness                   int64
anger                          int64
over.react                     int64
change.in.eating               int64
suicidal.thought               int64
feeling.tired                  int64
close.friend                   int64
social.media.addiction         int64
weight.gain                    int64
material.possessions           int64
introvert                      int64
popping.up.stressful.memory    int64
having.nightmares              int64
avoids.people.or.activities    int64
feeling.negative               int64
trouble.concentrating          int64
blamming.yourself              int64
dtype: object

In [16]:
Y

0           Anxiety
1        Depression
2        Loneliness
3            Stress
4            Normal
            ...    
40955       Anxiety
40956    Depression
40957    Loneliness
40958        Stress
40959        Normal
Name: Disorder, Length: 40960, dtype: object

In [17]:
Y.nunique()

5

In [18]:
Y.unique()

array(['Anxiety', 'Depression', 'Loneliness', 'Stress', 'Normal'],
      dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder

In [81]:
m = LabelEncoder()
Y = m.fit_transform(Y)
print(m.get_params)

<bound method BaseEstimator.get_params of LabelEncoder()>


In [83]:
Y

array([0, 1, 2, ..., 2, 4, 3], dtype=int64)

In [21]:
output

array([0, 1, 2, ..., 2, 4, 3])

In [23]:
X = np.array(df)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to

In [35]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [27]:
import tensorflow as tf

In [45]:
model = tf.keras.Sequential()

In [46]:
model.add(tf.keras.layers.Dense(24, activation = 'tanh'))
model.add(tf.keras.layers.Dense(16, activation = 'tanh'))
model.add(tf.keras.layers.Dense(10, activation = 'tanh'))
model.add(tf.keras.layers.Dense(5, activation = 'softmax'))

In [47]:
model.compile(optimizer = 'adam', loss = tf.keras.losses.SparseCategoricalCrossentropy())

In [48]:
model.fit(x = X_train, y = Y_train, batch_size = 512, epochs = 200, verbose = 1, validation_split= 0.3)

Epoch 1/200
45/45 [==============================] - 1s 12ms/step - loss: 0.9560 - val_loss: 0.5930
Epoch 2/200
45/45 [==============================] - 0s 5ms/step - loss: 0.4216 - val_loss: 0.2834
Epoch 3/200
45/45 [==============================] - 0s 5ms/step - loss: 0.2131 - val_loss: 0.1577
Epoch 4/200
45/45 [==============================] - 0s 5ms/step - loss: 0.1282 - val_loss: 0.1035
Epoch 5/200
45/45 [==============================] - 0s 5ms/step - loss: 0.0883 - val_loss: 0.0747
Epoch 6/200
45/45 [==============================] - 0s 5ms/step - loss: 0.0656 - val_loss: 0.0572
Epoch 7/200
45/45 [==============================] - 0s 5ms/step - loss: 0.0512 - val_loss: 0.0456
Epoch 8/200
45/45 [==============================] - 0s 5ms/step - loss: 0.0414 - val_loss: 0.0374
Epoch 9/200
45/45 [==============================] - 0s 6ms/step - loss: 0.0344 - val_loss: 0.0314
Epoch 10/200
45/45 [==============================] - 0s 5ms/step - loss: 0.0290 - val_loss: 0.0268
Epoch 11

Epoch 82/200
45/45 [==============================] - 0s 6ms/step - loss: 6.2085e-04 - val_loss: 6.1153e-04
Epoch 83/200
45/45 [==============================] - 0s 5ms/step - loss: 6.0296e-04 - val_loss: 5.9397e-04
Epoch 84/200
45/45 [==============================] - 0s 5ms/step - loss: 5.8569e-04 - val_loss: 5.7697e-04
Epoch 85/200
45/45 [==============================] - 0s 5ms/step - loss: 5.6901e-04 - val_loss: 5.6060e-04
Epoch 86/200
45/45 [==============================] - 0s 6ms/step - loss: 5.5288e-04 - val_loss: 5.4472e-04
Epoch 87/200
45/45 [==============================] - 0s 5ms/step - loss: 5.3730e-04 - val_loss: 5.2942e-04
Epoch 88/200
45/45 [==============================] - 0s 5ms/step - loss: 5.2222e-04 - val_loss: 5.1464e-04
Epoch 89/200
45/45 [==============================] - 0s 6ms/step - loss: 5.0764e-04 - val_loss: 5.0020e-04
Epoch 90/200
45/45 [==============================] - 0s 6ms/step - loss: 4.9350e-04 - val_loss: 4.8640e-04
Epoch 91/200
45/45 [========

45/45 [==============================] - 0s 5ms/step - loss: 8.7665e-05 - val_loss: 8.6618e-05
Epoch 158/200
45/45 [==============================] - 0s 5ms/step - loss: 8.5582e-05 - val_loss: 8.4519e-05
Epoch 159/200
45/45 [==============================] - 0s 5ms/step - loss: 8.3555e-05 - val_loss: 8.2563e-05
Epoch 160/200
45/45 [==============================] - 0s 5ms/step - loss: 8.1587e-05 - val_loss: 8.0607e-05
Epoch 161/200
45/45 [==============================] - 0s 5ms/step - loss: 7.9638e-05 - val_loss: 7.8675e-05
Epoch 162/200
45/45 [==============================] - 0s 5ms/step - loss: 7.7756e-05 - val_loss: 7.6839e-05
Epoch 163/200
45/45 [==============================] - 0s 5ms/step - loss: 7.5927e-05 - val_loss: 7.5026e-05
Epoch 164/200
45/45 [==============================] - 0s 5ms/step - loss: 7.4144e-05 - val_loss: 7.3237e-05
Epoch 165/200
45/45 [==============================] - 0s 5ms/step - loss: 7.2387e-05 - val_loss: 7.1544e-05
Epoch 166/200
45/45 [============

In [89]:
Y

array([0, 1, 2, ..., 2, 4, 3], dtype=int64)

In [44]:
Y_train

array([2, 1, 4, ..., 0, 1, 3])

In [55]:
rand = df.sample()

In [56]:
rand

feeling.nervous  panic  breathing.rapidly  sweating  \
25924                0      0                  0         0   

       trouble.in.concentration  having.trouble.in.sleeping  \
25924                         0                           0   

       having.trouble.with.work  hopelessness  anger  over.react  ...  \
25924                         0             0      0           0  ...   

       social.media.addiction  weight.gain  material.possessions  introvert  \
25924                       0            0                     0          0   

       popping.up.stressful.memory  having.nightmares  \
25924                            0                  0   

       avoids.people.or.activities  feeling.negative  trouble.concentrating  \
25924                            0                 0                      0   

       blamming.yourself  
25924                  0  

[1 rows x 24 columns]

In [57]:
act = Y[rand.index]

In [63]:
act.shape

(1,)

In [59]:
model.predict(np.array(rand))

1/1 [==============================] - 0s 27ms/step


array([[2.6300288e-06, 1.4372972e-05, 1.0902892e-05, 9.9997211e-01,
        4.2731816e-08]], dtype=float32)

In [70]:
prediction = model.predict(X_test).argmax(axis = 1)

256/256 [==============================] - 1s 2ms/step


In [72]:
print(np.mean(prediction == Y_test) * 100)

100.0


In [75]:
model.save("mental_health_status.h5",)

In [92]:
{0 : "Anxiety", 1 : "Depression", 2 : "Loneliness", 3 : "Normal", 4 : "Stress"}

{0: 'Anxiety', 1: 'Depression', 2: 'Loneliness', 3: 'Normal', 4: 'Stress'}

In [84]:
Y

array([0, 1, 2, ..., 2, 4, 3], dtype=int64)

In [86]:
df1 = pd.read_csv("dataset.csv")

In [87]:
df1

feeling.nervous panic breathing.rapidly sweating  \
0                 yes   yes               yes      yes   
1                  no    no                no       no   
2                  no    no                no       no   
3                  no    no                no       no   
4                  no    no                no       no   
...               ...   ...               ...      ...   
40955             yes   yes               yes      yes   
40956              no    no                no       no   
40957              no    no                no       no   
40958              no    no                no       no   
40959              no    no                no       no   

      trouble.in.concentration having.trouble.in.sleeping  \
0                          yes                        yes   
1                           no                         no   
2                           no                         no   
3                           no                         no   
4                           no                         no   
...                        ...                        ...   
40955                      yes                        yes   
40956                       no                         no   
40957                       no                         no   
40958                       no                         no   
40959                       no                         no   

      having.trouble.with.work hopelessness anger over.react  ... weight.gain  \
0                           no           no    no         no  ...          no   
1                          yes          yes   yes        yes  ...          no   
2                           no           no    no         no  ...         yes   
3                           no           no    no         no  ...          no   
4                           no           no    no         no  ...          no   
...                        ...          ...   ...        ...  ...         ...   
40955                       no           no    no         no  ...          no   
40956                      yes          yes   yes        yes  ...          no   
40957                       no           no    no         no  ...         yes   
40958                       no           no    no         no  ...          no   
40959                       no           no    no         no  ...          no   

      material.possessions introvert popping.up.stressful.memory  \
0                       no        no                          no   
1                       no        no                          no   
2                      yes       yes                          no   
3                       no        no                         yes   
4                       no        no                          no   
...                    ...       ...                         ...   
40955                   no        no                          no   
40956                   no        no                          no   
40957                  yes       yes                          no   
40958                   no        no                         yes   
40959                   no        no                          no   

      having.nightmares avoids.people.or.activities feeling.negative  \
0                    no                          no               no   
1                    no                          no               no   
2                    no                          no               no   
3                   yes                         yes              yes   
4                    no                          no               no   
...                 ...                         ...              ...   
40955                no                          no               no   
40956                no                          no               no   
40957                no                          no               no   
40958               yes                         yes              y